#define GAME_MOUSE_SENSITIVITY   0.001f
#define GAME_MOUSE_SMOOTH        0.5f
#define GAME_WALK_SPEED          2.9f
#define GAME_WALK_ACCEL          20.0f
#define GAME_BOB_FREQ			 8.0f
#define GAME_BOB_OFFS			 0.015f
#define GAME_BOB_DAMP			 0.04f
#define GAME_BOB_MIN			 0.1f
#define GAME_DELTATIME           0.002f
#define GAME_UPDATES_PER_SECOND  500
#define GAME_RENDERS_PER_SECOND  90
#define GAME_MAX_STEPS           30
#define GAME_PLAYER_HEIGHT       1.5f
#define GAME_PLAYER_RADIUS       0.2f
#define GAME_GRAVITY            -9.8f

#define CAMERA_DEFAULT_FOV  65.0f
#define CAMERA_DEFAULT_NEAR 0.001f
#define CAMERA_DEFAULT_FAR  100.0f